build:
  buildpacks:
    - heroku/python
  env:
    - PYTHONPATH=/app
deploy:
  env:
    - PYTHONUNBUFFERED=1
    - PORT=8000
  command: gunicorn project_recruitment.wsgi:application --bind 0.0.0.0:$PORT