# Generated by Django 5.2 on 2025-04-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
    ]
