# Generated by Django 5.2 on 2025-04-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_create_initial_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='block',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='session',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='SimulationBlock',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='SimulationResult',
        ),
        migrations.DeleteModel(
            name='SimulationSession',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
