# Generated by Django 5.2 on 2025-04-14 16:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Відповідь', 'verbose_name_plural': 'Відповіді'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['block', 'order'], 'verbose_name': 'Питання', 'verbose_name_plural': 'Питання'},
        ),
        migrations.AlterModelOptions(
            name='simulationblock',
            options={'ordering': ['order'], 'verbose_name': 'Блок симуляції', 'verbose_name_plural': 'Блоки симуляції'},
        ),
        migrations.AlterModelOptions(
            name='simulationresult',
            options={'verbose_name': 'Результат симуляції', 'verbose_name_plural': 'Результати симуляції'},
        ),
        migrations.AlterModelOptions(
            name='simulationsession',
            options={'verbose_name': 'Сесія симуляції', 'verbose_name_plural': 'Сесії симуляції'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Відповідь користувача', 'verbose_name_plural': 'Відповіді користувачів'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='simulationsession',
            name='id',
        ),
        migrations.AddField(
            model_name='answer',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Пояснення'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок у блоці'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час відповіді'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильна відповідь'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='simulation.question', verbose_name='Питання'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='Текст відповіді'),
        ),
        migrations.AlterField(
            model_name='question',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='simulation.simulationblock', verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=1, verbose_name='Бали за правильну відповідь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст питання'),
        ),
        migrations.AlterField(
            model_name='simulationblock',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис блоку'),
        ),
        migrations.AlterField(
            model_name='simulationblock',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок відображення'),
        ),
        migrations.AlterField(
            model_name='simulationblock',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва блоку'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='completed_at',
            field=models.DateTimeField(verbose_name='Час завершення'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='max_score',
            field=models.IntegerField(default=0, verbose_name='Максимальний можливий бал'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='simulation.simulationsession', verbose_name='Сесія'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='Загальний бал'),
        ),
        migrations.AlterField(
            model_name='simulationsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='simulationsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False, editable=False, verbose_name='Правильна відповідь'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.question', verbose_name='Питання'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.answer', verbose_name='Обрана відповідь'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='simulation.simulationsession', verbose_name='Сесія'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('session', 'question')},
        ),
    ]
