# Generated by Django 5.2 on 2025-04-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['block', 'order']},
        ),
        migrations.AlterModelOptions(
            name='simulationsession',
            options={},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='explanation',
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок у блоках'),
        ),
        migrations.AlterField(
            model_name='simulationsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='simulation.simulationsession', verbose_name='Сесія'),
        ),
    ]
